sudo: false
addons:
  firefox: "53.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -zxvf geckodriver-v0.16.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -e ."
script: nose2 planterbox_webdriver
after_script:
- cat geckodriver.log
